const LOGGER_ROUTES = {
	BASE: 'BASE',
	USERS: 'USERS',
	MOVIES: 'MOVIES',
	TOKEN_AUTHENTICATION: 'TOKEN AUTHENTICATION',
} as const;

type LoggerRoutTypes = {
	BASE: typeof LOGGER_ROUTES.BASE;
	USERS: typeof LOGGER_ROUTES.USERS;
	MOVIES: typeof LOGGER_ROUTES.MOVIES;
	TOKEN_AUTHENTICATION: typeof LOGGER_ROUTES.TOKEN_AUTHENTICATION;
};

type LOGGER_ROUTES_KEYS = keyof LoggerRoutTypes;
type LOGGER_ROUTE_VALUES = LoggerRoutTypes[LOGGER_ROUTES_KEYS];

export { LOGGER_ROUTES, LOGGER_ROUTES_KEYS, LOGGER_ROUTE_VALUES };
