type LOGGER_ROUTE_TYPES = {
  BASE: 'BASE';
  USERS: 'USERS';
  MOVIES: 'MOVIES';
  TOKEN_AUTHENTICATION: 'TOKEN AUTHENTICATION';
};

const LOGGER_ROUTES: LOGGER_ROUTE_TYPES = {
  BASE: 'BASE',
  USERS: 'USERS',
  MOVIES: 'MOVIES',
  TOKEN_AUTHENTICATION: 'TOKEN AUTHENTICATION',
} as const;

type LOGGER_ROUTES_KEYS = keyof LOGGER_ROUTE_TYPES;
type LOGGER_ROUTE_VALUES = LOGGER_ROUTE_TYPES[LOGGER_ROUTES_KEYS];

export { LOGGER_ROUTES, LOGGER_ROUTES_KEYS, LOGGER_ROUTE_VALUES };
