type STATUS_CODES_TYPE = {
  OK: 200;
  CREATED: 201;
  BAD_REQUEST: 400;
  UNAUTHORIZED: 401;
  NOT_FOUND: 404;
  SERVER_ERROR: 500;
};

const STATUS_CODES: STATUS_CODES_TYPE = {
  OK: 200,
  CREATED: 201,
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  NOT_FOUND: 404,
  SERVER_ERROR: 500,
};

type STATUS_CODES_KEYS = keyof STATUS_CODES_TYPE;
type STATUS_CODES_VALUES = STATUS_CODES_TYPE[STATUS_CODES_KEYS];

export { STATUS_CODES, STATUS_CODES_KEYS, STATUS_CODES_VALUES };
